
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author princ
 */
public class POS extends javax.swing.JFrame {
String iTax, iSubTotal, iTotal;
double [] itemcost = new double[15];
    /**
     * Creates new form POS
     */
    public POS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BBrinjal = new javax.swing.JButton();
        BOnion = new javax.swing.JButton();
        BMushroom = new javax.swing.JButton();
        BBeans = new javax.swing.JButton();
        BGinger = new javax.swing.JButton();
        BGarlic = new javax.swing.JButton();
        BCoconut = new javax.swing.JButton();
        Btomato = new javax.swing.JButton();
        BPotato = new javax.swing.JButton();
        BCarrot = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        CBeans = new javax.swing.JCheckBox();
        TPotato = new javax.swing.JTextField();
        CBrinjal = new javax.swing.JCheckBox();
        COnion = new javax.swing.JCheckBox();
        CMushroom = new javax.swing.JCheckBox();
        CGinger = new javax.swing.JCheckBox();
        CGarlic = new javax.swing.JCheckBox();
        CTomato = new javax.swing.JCheckBox();
        CPotato = new javax.swing.JCheckBox();
        CCarrot = new javax.swing.JCheckBox();
        CCoconut = new javax.swing.JCheckBox();
        TBrinjal = new javax.swing.JTextField();
        TTomato = new javax.swing.JTextField();
        TMushroom = new javax.swing.JTextField();
        TBeans = new javax.swing.JTextField();
        TGinger = new javax.swing.JTextField();
        TOnion = new javax.swing.JTextField();
        TGarlic = new javax.swing.JTextField();
        TCoconut = new javax.swing.JTextField();
        TCarrot = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        LTotal = new javax.swing.JLabel();
        TTotal = new javax.swing.JTextField();
        LTotal1 = new javax.swing.JLabel();
        TSubTotal = new javax.swing.JTextField();
        TTax = new javax.swing.JTextField();
        LTotal2 = new javax.swing.JLabel();
        jbtnConfirm = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtreceipt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        BBrinjal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BBrinjal.setText("BRINJAL");
        BBrinjal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBrinjalActionPerformed(evt);
            }
        });

        BOnion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BOnion.setText("ONION");
        BOnion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOnionActionPerformed(evt);
            }
        });

        BMushroom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BMushroom.setText("MUSHROOM");
        BMushroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMushroomActionPerformed(evt);
            }
        });

        BBeans.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BBeans.setText("BEANS");
        BBeans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBeansActionPerformed(evt);
            }
        });

        BGinger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BGinger.setText("GINGER");
        BGinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGingerActionPerformed(evt);
            }
        });

        BGarlic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BGarlic.setText("GARLIC");
        BGarlic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGarlicActionPerformed(evt);
            }
        });

        BCoconut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BCoconut.setText("COCONUT");
        BCoconut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCoconutActionPerformed(evt);
            }
        });

        Btomato.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btomato.setText("TOMATO");
        Btomato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtomatoActionPerformed(evt);
            }
        });

        BPotato.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BPotato.setText("POTATO");
        BPotato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPotatoActionPerformed(evt);
            }
        });

        BCarrot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BCarrot.setText("CARROT");
        BCarrot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCarrotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BCarrot, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BPotato, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btomato, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BBrinjal, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOnion, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BMushroom, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BBeans, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BGinger, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BGarlic, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCoconut, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(Btomato, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BPotato, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BBrinjal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BOnion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BMushroom, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BBeans, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BGinger, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BGarlic, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BCoconut, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BCarrot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        CBeans.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBeans.setText("BEANS");
        CBeans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBeansActionPerformed(evt);
            }
        });

        TPotato.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TPotato.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TPotato.setToolTipText("");
        TPotato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TPotatoKeyTyped(evt);
            }
        });

        CBrinjal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBrinjal.setText("BRINJAL");
        CBrinjal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBrinjalActionPerformed(evt);
            }
        });

        COnion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        COnion.setText("ONION");
        COnion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COnionActionPerformed(evt);
            }
        });

        CMushroom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CMushroom.setText("MUSHROOM");
        CMushroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMushroomActionPerformed(evt);
            }
        });

        CGinger.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CGinger.setText("GINGER");
        CGinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CGingerActionPerformed(evt);
            }
        });

        CGarlic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CGarlic.setText("GARLIC");
        CGarlic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CGarlicActionPerformed(evt);
            }
        });

        CTomato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CTomato.setText("TOMATO");
        CTomato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTomatoActionPerformed(evt);
            }
        });

        CPotato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CPotato.setText("POTATO");
        CPotato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPotatoActionPerformed(evt);
            }
        });

        CCarrot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CCarrot.setText("CARROT");
        CCarrot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCarrotActionPerformed(evt);
            }
        });

        CCoconut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CCoconut.setText("COCONUT");
        CCoconut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCoconutActionPerformed(evt);
            }
        });

        TBrinjal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TBrinjal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TBrinjal.setToolTipText("");
        TBrinjal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TBrinjalKeyTyped(evt);
            }
        });

        TTomato.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TTomato.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TTomato.setToolTipText("");
        TTomato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TTomatoKeyTyped(evt);
            }
        });

        TMushroom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TMushroom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TMushroom.setToolTipText("");
        TMushroom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TMushroomKeyTyped(evt);
            }
        });

        TBeans.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TBeans.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TBeans.setToolTipText("");
        TBeans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TBeansKeyTyped(evt);
            }
        });

        TGinger.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TGinger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TGinger.setToolTipText("");
        TGinger.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TGingerKeyTyped(evt);
            }
        });

        TOnion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TOnion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TOnion.setToolTipText("");
        TOnion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TOnionKeyTyped(evt);
            }
        });

        TGarlic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TGarlic.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TGarlic.setToolTipText("");
        TGarlic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TGarlicKeyTyped(evt);
            }
        });

        TCoconut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TCoconut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TCoconut.setToolTipText("");
        TCoconut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TCoconutKeyTyped(evt);
            }
        });

        TCarrot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TCarrot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TCarrot.setToolTipText("");
        TCarrot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TCarrotKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CCoconut, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(CPotato, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TPotato, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CMushroom, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(CTomato, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(TTomato, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(COnion, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CBrinjal, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CBeans, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CGinger, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CGarlic, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CCarrot, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(58, 58, 58)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TCarrot, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TGarlic, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TGinger, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TBeans, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TBrinjal, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TMushroom, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TOnion, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TCoconut, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CTomato, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TTomato, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPotato, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TPotato, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBrinjal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TBrinjal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(COnion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TOnion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CMushroom, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TMushroom, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBeans, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TBeans, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CGinger, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TGinger, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CGarlic, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TGarlic, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CCoconut, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCoconut, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CCarrot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCarrot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        LTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LTotal.setText("TOTAL            :");

        LTotal1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LTotal1.setText("SUB TOTAL    :");

        LTotal2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LTotal2.setText("TAX                :");

        jbtnConfirm.setText("CONFIRM");
        jbtnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmActionPerformed(evt);
            }
        });

        jbtnReset.setText("RESET");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnExit.setText("EXIT");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jtxtreceipt.setColumns(20);
        jtxtreceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtreceipt);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TTax, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jbtnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TTax, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Sure you want to Exit?","Point of Sale",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
        System.exit(0);
    }
    }                                        

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {                                          

        // TODO add your handling code here:
        TTomato.setText("0");
        CTomato.setSelected(false);
        TPotato.setText("0");
        CPotato.setSelected(false);
        TOnion.setText("0");
        COnion.setSelected(false);
        TBrinjal.setText("0");
        CBrinjal.setSelected(false);
        TMushroom.setText("0");
        CMushroom.setSelected(false);
        TBeans.setText("0");
        CBeans.setSelected(false);
        TGinger.setText("0");
        CGinger.setSelected(false);
        TGarlic.setText("0");
        CGarlic.setSelected(false);
        TCoconut.setText("0");
        CCoconut.setSelected(false);
        TCarrot.setText("0");
        CCarrot.setSelected(false);
        
        TTomato.setEnabled(false);
        TPotato.setEnabled(false);
        TBrinjal.setEnabled(false);
        TOnion.setEnabled(false);
        TMushroom.setEnabled(false);
        TGarlic.setEnabled(false);
        TGinger.setEnabled(false);
        TBeans.setEnabled(false);
        TCoconut.setEnabled(false);
        TCarrot.setEnabled(false);
        TTax.setEnabled(false);
        TSubTotal.setEnabled(false);
        TTotal.setEnabled(false);
        jtxtreceipt.setEnabled(false);
        
        CTomato.setEnabled(false);
        CPotato.setEnabled(false);
        CBrinjal.setEnabled(false);
        COnion.setEnabled(false);
        CMushroom.setEnabled(false);
        CCarrot.setEnabled(false);
        CGinger.setEnabled(false);
        CGarlic.setEnabled(false);
        CCoconut.setEnabled(false);
        CBeans.setEnabled(false);
        
    }                                         

    private void TTomatoKeyTyped(java.awt.event.KeyEvent evt) {                                 

        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }                                

    private void TPotatoKeyTyped(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }                                

    private void TBrinjalKeyTyped(java.awt.event.KeyEvent evt) {                                  
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }                                 

    private void TOnionKeyTyped(java.awt.event.KeyEvent evt) {                                
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }                               

    private void TMushroomKeyTyped(java.awt.event.KeyEvent evt) {                                   
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }                                  

    private void TBeansKeyTyped(java.awt.event.KeyEvent evt) {                                
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }                               

    private void TGingerKeyTyped(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }                                

    private void TGarlicKeyTyped(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }                                

    private void TCoconutKeyTyped(java.awt.event.KeyEvent evt) {                                  
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }                                 

    private void TCarrotKeyTyped(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }                                

    private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
        // TODO add your handling code here:
        TTomato.setEnabled(false);
        TPotato.setEnabled(false);
        TBrinjal.setEnabled(false);
        TOnion.setEnabled(false);
        TMushroom.setEnabled(false);
        TGarlic.setEnabled(false);
        TGinger.setEnabled(false);
        TBeans.setEnabled(false);
        TCoconut.setEnabled(false);
        TCarrot.setEnabled(false);
        TTax.setEnabled(false);
        TSubTotal.setEnabled(false);
        TTotal.setEnabled(false);
        jtxtreceipt.setEnabled(false);
        
        CTomato.setEnabled(false);
        CPotato.setEnabled(false);
        CBrinjal.setEnabled(false);
        COnion.setEnabled(false);
        CMushroom.setEnabled(false);
        CCarrot.setEnabled(false);
        CGinger.setEnabled(false);
        CGarlic.setEnabled(false);
        CCoconut.setEnabled(false);
        CBeans.setEnabled(false);
        
        
        
    }                                    

    private void BtomatoActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        CTomato.setEnabled(true);
        
    }                                       

    private void BPotatoActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        CPotato.setEnabled(true);
    }                                       

    private void BBrinjalActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        CBrinjal.setEnabled(true);
    }                                        

    private void BOnionActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        COnion.setEnabled(true);
    }                                      

    private void BMushroomActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        CMushroom.setEnabled(true);
    }                                         

    private void BBeansActionPerformed(java.awt.event.ActionEvent evt) {                                       
        CBeans.setEnabled(true);// TODO add your handling code here:
    }                                      

    private void BGingerActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        CGinger.setEnabled(true);
    }                                       

    private void BGarlicActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        CGarlic.setEnabled(true);
    }                                       

    private void BCoconutActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        CCoconut.setEnabled(true);
    }                                        

    private void BCarrotActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        CCarrot.setEnabled(true);
    }                                       

    private void CTomatoActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        if(CTomato.isSelected()){
            TTomato.setEnabled(true);
            TTomato.setText("");
            TTomato.requestFocus();
        }
        else
            TTomato.setEnabled(false);
        TTomato.setText("0");
            
        
    }                                       

    private void CPotatoActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        if(CPotato.isSelected()){
            TPotato.setEnabled(true);
            TPotato.setText("");
            TPotato.requestFocus();
        }
        else
            TPotato.setEnabled(false);
        TPotato.setText("0");
    }                                       

    private void CBrinjalActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if(CBrinjal.isSelected()){
            TBrinjal.setEnabled(true);
            TBrinjal.setText("");
            TBrinjal.requestFocus();
        }
        else
            TBrinjal.setEnabled(false);
        TBrinjal.setText("0");
    }                                        

    private void COnionActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        if(COnion.isSelected()){
            TOnion.setEnabled(true);
            TOnion.setText("");
            TOnion.requestFocus();
        }
        else
            TOnion.setEnabled(false);
        TOnion.setText("0");
    }                                      

    private void CMushroomActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if(CMushroom.isSelected()){
            TMushroom.setEnabled(true);
            TMushroom.setText("");
            TMushroom.requestFocus();
        }
        else
            TMushroom.setEnabled(false);
        TMushroom.setText("0");
    }                                         

    private void CBeansActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        if(CBeans.isSelected()){
            TBeans.setEnabled(true);
            TBeans.setText("");
            TBeans.requestFocus();
        }
        else
            TBeans.setEnabled(false);
        TBeans.setText("0");
    }                                      

    private void CGingerActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        if(CGinger.isSelected()){
            TGinger.setEnabled(true);
            TGinger.setText("");
            TGinger.requestFocus();
        }
        else
            TGinger.setEnabled(false);
        TGinger.setText("0");
    }                                       

    private void CGarlicActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        if(CGarlic.isSelected()){
            TGarlic.setEnabled(true);
            TGarlic.setText("");
            TGarlic.requestFocus();
        }
        else
            TGarlic.setEnabled(false);
        TGarlic.setText("0");
    }                                       

    private void CCoconutActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if(CCoconut.isSelected()){
            TCoconut.setEnabled(true);
            TCoconut.setText("");
            TCoconut.requestFocus();
        }
        else
            TCoconut.setEnabled(false);
        TCoconut.setText("0");
    }                                        

    private void CCarrotActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        if(CCarrot.isSelected()){
            TCarrot.setEnabled(true);
            TCarrot.setText("");
            TCarrot.requestFocus();
        }
        else
            TCarrot.setEnabled(false);
        TCarrot.setText("0");
    }                                       

    private void jbtnConfirmActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        
        itemcost[0] = Double.parseDouble(TTomato.getText()) * 20;
        itemcost[1] = Double.parseDouble(TPotato.getText()) * 25;
        itemcost[2] = Double.parseDouble(TBrinjal.getText()) * 50;
        itemcost[3] = Double.parseDouble(TOnion.getText()) * 15;
        itemcost[4] = Double.parseDouble(TMushroom.getText()) * 30;
        itemcost[5] = Double.parseDouble(TBeans.getText()) * 25;
        itemcost[6] = Double.parseDouble(TGinger.getText()) * 20;
        itemcost[7] = Double.parseDouble(TGarlic.getText()) * 30;
        itemcost[8] = Double.parseDouble(TCoconut.getText()) * 90;
        itemcost[9] = Double.parseDouble(TCarrot.getText()) * 40;
        
        itemcost[10] = (itemcost[0]+itemcost[1]+itemcost[2]+itemcost[3]+itemcost[4]);
        itemcost[11] = itemcost[5]+itemcost[6]+itemcost[7]+itemcost[8]+itemcost[9];
        itemcost[12] = itemcost[10] + itemcost[11];
        
        iSubTotal = String.format("Rs. %2f",itemcost[12]);
        iTax = String.format("Rs. %2f",(itemcost[12]*0.20));
        iTotal = String.format("Rs. %2f", itemcost[12] + (itemcost[12]/100));
       
       
       TTax.setText(iTax);
       TSubTotal.setText(iSubTotal);
       TTotal.setText(iTotal);
       
       jtxtreceipt.setEnabled(true);
       int refs = 1325 + (int)(Math.random()*4238);
       
       Calendar timer = Calendar.getInstance();
       timer.getTime();
       SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
       tTime.format(timer.getTime());
       SimpleDateFormat tDate = new SimpleDateFormat("dd-MMM-yyyy");
       tDate.format(timer.getTime());
       
       jtxtreceipt.append("POS\n"+"Reference:\t\t\t\t" + refs+ "\n=========================================================\t" +
               "\n=========================================================\t"+"\nTax :\t\t\t"+iTax+"\nSub Total:\t\t\t"+iSubTotal+"\nTotal:\t\t\t"+iTotal+"\n=========================================================\t"+
       "\nDate: "+tDate.format(timer.getTime())+"\t\tTime: "+tTime.format(timer.getTime()));
       
       
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BBeans;
    private javax.swing.JButton BBrinjal;
    private javax.swing.JButton BCarrot;
    private javax.swing.JButton BCoconut;
    private javax.swing.JButton BGarlic;
    private javax.swing.JButton BGinger;
    private javax.swing.JButton BMushroom;
    private javax.swing.JButton BOnion;
    private javax.swing.JButton BPotato;
    private javax.swing.JButton Btomato;
    private javax.swing.JCheckBox CBeans;
    private javax.swing.JCheckBox CBrinjal;
    private javax.swing.JCheckBox CCarrot;
    private javax.swing.JCheckBox CCoconut;
    private javax.swing.JCheckBox CGarlic;
    private javax.swing.JCheckBox CGinger;
    private javax.swing.JCheckBox CMushroom;
    private javax.swing.JCheckBox COnion;
    private javax.swing.JCheckBox CPotato;
    private javax.swing.JCheckBox CTomato;
    private javax.swing.JLabel LTotal;
    private javax.swing.JLabel LTotal1;
    private javax.swing.JLabel LTotal2;
    private javax.swing.JTextField TBeans;
    private javax.swing.JTextField TBrinjal;
    private javax.swing.JTextField TCarrot;
    private javax.swing.JTextField TCoconut;
    private javax.swing.JTextField TGarlic;
    private javax.swing.JTextField TGinger;
    private javax.swing.JTextField TMushroom;
    private javax.swing.JTextField TOnion;
    private javax.swing.JTextField TPotato;
    private javax.swing.JTextField TSubTotal;
    private javax.swing.JTextField TTax;
    private javax.swing.JTextField TTomato;
    private javax.swing.JTextField TTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnConfirm;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JTextArea jtxtreceipt;
    // End of variables declaration                   
}